```go
package main

type customError struct {
	msg string
}

func (e *customError) Error() string {
	return e.msg
}

func test() *customError {
	{
		// do something
	}
	return nil
}

func main() {
	var err error

	err = test()
	if err != nil {
		println("error")
		return
	}
	println("ok")
}
```
Данные код выведет 
```
error
```

# Пояснение

Дело в том, что функция `test()` запишет в `err` интерфейсную переменную интерфейса `error` с типом `*customError` и значением `nil`. 
Далее при сравнении с `nil` выражение `err != nil` будет `true`, т.к. в переменной интерфейса `error` только значение равно `nil`, а тип равен `*customError`, а не nil.
Это выражение было бы `false` только если бы и тип внутри интерфейса `error` был бы равен `nil`  